### ISSUE TITLE
Support [hash], [contenthash] and etc from loader-utils

### ISSUE THREAD

**Issue by alexander-akait** [NMFR/last-call-webpack-plugin#1]
Using `filename: "[name]-[contenthash].css"` in `extract-text-webpack-plugin`, i have file like `app-6f8bbde7c2.css`, but after using `cssnano` content changed and `[contexthash]` now is invalid. 

Can we add `filename` option as in `extract-text-webpack-plugin` for changing hash or pass`assetName` in `onEnd` callback (also support async callback or promise)?

**Comment by NMFR** [comment]
You want the ability to change the assets name, is that it?

**Comment by alexander-akait** [comment]
@NMFR In theory yes, in practice change content hash, because we have changed file content

**Comment by NMFR** [comment]
OK. `last-call-webpack-plugin` should be abstracted from that, but changing the asset's name is a feature that makes sense.

**Comment by NMFR** [comment]
Version `v2.1.1` added this :)

``` javascript
var cssnano = require('cssnano');
var LastCallWebpackPlugin = require('last-call-webpack-plugin');
module.exports = {
  module: {
    loaders: [
      { test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader") }
    ]
  },
  plugins: [
    new ExtractTextPlugin("styles.css"),
    new LastCallWebpackPlugin({
      assetProcessors: [{
        regExp:  /\.css$/,
        processor: (assetName, asset, assets) => {
          assets.setAsset(assetName + '.map', null); // Delete the <assetName>.map asset.
          assets.setAsset(assetName + '.log', 'All OK'); // Add the <assetName>.log asset with the content 'All OK'.
          return cssnano
            .process(asset.source())
            .then(r => r.css)
        }
      }],
      onStart: () => console.log('Starting to process assets.'),
      onEnd: (err) => console.log(err ? 'Error: ' + err : 'Finished processing assets.'),
      canPrint: true
    })
	]
}
```

**Comment by PutziSan** [comment]
I think this is related to https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/56?!

So I don't think the real issue has been solved yet, or what do you think @NMFR ?
