### ISSUE TITLE
How to process asset with sourceMap?

### ISSUE THREAD

**Issue by shkarupa-alex** [NMFR/last-call-webpack-plugin#2]
I've got CSS with source map.
During processing source map changes.

So how can i put just generated source map back to assets?

**Comment by NMFR** [comment]
You need to configure whatever package you are using to manipulate CSS to emit source maps.
This might be a problem if you want to generate additional files (because this plugin is not ready for that at the moment). But if you generate inline source maps, it should work ok.

**Comment by NMFR** [comment]
Version `v2.1.1` now allows the creation and deletion of other assets.

Should make source map handling easier.
